### ISSUE TITLE
Add a composer.json

### ISSUE THREAD

**Issue by xaqrox** [alleyinteractive/stage-file-proxy#15]
To add stage-file-proxy to a composer-managed Wordpress project one must add the following to their composer.json in every project:

```json
"repositories": [
  {
    "type": "package",
    "package": {
      "name": "alleyinteractive/stage-file-proxy",
      "version": "dev-main",
      "type": "wordpress-plugin",
      "source": {
        "url": "https://github.com/alleyinteractive/stage-file-proxy.git",
        "type": "git",
        "reference": "main"
      }
    }
  }
]
```

If this project maintained it's own composer.json then it'd be as simple as:

```json
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/alleyinteractive/stage-file-proxy"
  }
]
```

(With the obvious end goal of getting this on a package manager so we can just `composer require alleyinteractive/stage-file-proxy`)

**Comment by dlh01** [comment]
Thanks for filing this @xaqrox! The repository now has a `composer.json` and is available on Packagist: https://packagist.org/packages/alleyinteractive/stage-file-proxy. Please check back if you have any trouble installing it.
